version: '3.8'

networks:
  ssmanageadapter:
    driver: bridge

services:
  ssmanageadapterdbhost:
    container_name: ssmanageadapterdbhost
    hostname: ssmanageadapterdbhost
    image: postgres:12
    env_file:
      - ./.env
    ports:
      - $POSTGRES_EXTERNAL_PORT:$POSTGRES_INTERNAL_PORT
    networks:
      ssmanageadapter:
          null
    restart: unless-stopped
    volumes:
      - $MOUNT_PGDATA:$PGDATA
  ssmanageadapterapi:
    container_name: ssmanageadapterapi
    hostname: ssmanageadapterapi
    env_file:
      - ./.env
    build:
      context: ./ssmanageadapter
      dockerfile: Dockerfile
      args:
        - SERVER_INTERNAL_PORT=$SERVER_INTERNAL_PORT
        - POSTGRES_HOST=$POSTGRES_HOST
        - POSTGRES_INTERNAL_PORT=$POSTGRES_INTERNAL_PORT
        - POSTGRES_DB=$POSTGRES_DB
        - POSTGRES_USER=$POSTGRES_USER
        - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
        - API_WORK_DIR=$API_WORK_DIR
        - MAIL_HOST=$MAIL_HOST
        - MAIL_PORT=$MAIL_PORT
        - MAIL_USERNAME=$MAIL_USERNAME
        - MAIL_PASSWORD=$MAIL_PASSWORD
        - MAIL_PROPERTIES_MAIL_SMTP_AUTH=$MAIL_PROPERTIES_MAIL_SMTP_AUTH
        - MAIL_PROPERTIES_MAIL_SMTP_STARTTLS_ENABLE=$MAIL_PROPERTIES_MAIL_SMTP_STARTTLS_ENABLE
    depends_on:
      - ssmanageadapterdbhost
    ports:
      - $SERVER_EXTERNAL_PORT:$SERVER_INTERNAL_PORT
    networks:
      ssmanageadapter:
          null
    restart: unless-stopped
    volumes:
      - ./ssmanageadapter/src/main/:$API_WORK_DIR/src/main
      - ./ssmanageadapter/src/test:$API_WORK_DIR/src/test
      - ./ssmanageadapter/target:$API_WORK_DIR/target
      - ./ssmanageadapter/libs:$API_WORK_DIR/libs
      - ./ssmanageadapter/:$API_WORK_DIR
  ssmanageadapterweb:
    container_name: ssmanageadapterweb
    hostname: ssmanageadapterweb
    env_file:
      - ./.env
    build:
      context: ./web
      dockerfile: Dockerfile
      args:
        - WEB_WORK_DIR=$WEB_WORK_DIR
    ports:
      - $WEB_EXTERNAL_PORT:$WEB_INTERNAL_PORT
    volumes:
      - ./web/src:$WEB_WORK_DIR/src
      - ./web/config:$WEB_WORK_DIR/config
    networks:
      ssmanageadapter:
          null
    restart: unless-stopped
