version: '3.8'

networks:
  csadapter:
    driver: bridge

services:
  csadapterdbhost:
    container_name: csadapterdbhost
    hostname: csadapterdbhost
    image: postgres:12
    env_file:
      - ./.env
    ports:
      - $POSTGRES_EXTERNAL_PORT:$POSTGRES_INTERNAL_PORT
    networks:
      csadapter:
          null
    restart: unless-stopped
    volumes:
      - $MOUNT_PGDATA:$PGDATA
  csadapterapi:
    container_name: csadapterapi
    hostname: csadapterapi
    env_file:
      - ./.env
    build:
      context: ./csadapter
      dockerfile: Dockerfile
      args:
        - SERVER_INTERNAL_PORT=$SERVER_INTERNAL_PORT
        - POSTGRES_HOST=$POSTGRES_HOST
        - POSTGRES_INTERNAL_PORT=$POSTGRES_INTERNAL_PORT
        - POSTGRES_DB=$POSTGRES_DB
        - POSTGRES_USER=$POSTGRES_USER
        - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
        - API_WORK_DIR=$API_WORK_DIR
        - MAIL_HOST=$MAIL_HOST
        - MAIL_PORT=$MAIL_PORT
        - MAIL_USERNAME=$MAIL_USERNAME
        - MAIL_PASSWORD=$MAIL_PASSWORD
        - MAIL_PROPERTIES_MAIL_SMTP_AUTH=$MAIL_PROPERTIES_MAIL_SMTP_AUTH
        - MAIL_PROPERTIES_MAIL_SMTP_STARTTLS_ENABLE=$MAIL_PROPERTIES_MAIL_SMTP_STARTTLS_ENABLE
    depends_on:
      - csadapterdbhost
    ports:
      - $SERVER_EXTERNAL_PORT:$SERVER_INTERNAL_PORT
    networks:
      csadapter:
          null
    restart: unless-stopped
    volumes:
      - ./csadapter/src/main/:$API_WORK_DIR/src/main
      - ./csadapter/src/test:$API_WORK_DIR/src/test
      - ./csadapter/target:$API_WORK_DIR/target
      - ./csadapter/libs:$API_WORK_DIR/libs
      - ./csadapter/:$API_WORK_DIR
  # csadapterweb:
  #   container_name: csadapterweb
  #   hostname: csadapterweb
  #   env_file:
  #     - ./.env
  #   build:
  #     context: ./web
  #     dockerfile: Dockerfile
  #     args:
  #       - WEB_WORK_DIR=$WEB_WORK_DIR
  #   ports:
  #     - $WEB_EXTERNAL_PORT:$WEB_INTERNAL_PORT
  #   volumes:
  #     - ./web/src:$WEB_WORK_DIR/src
  #     - ./web/config:$WEB_WORK_DIR/config
  #   networks:
  #     csadapter:
  #         null
  #   restart: unless-stopped
