version: '3.8'

networks:
  qlvb:
    driver: bridge

services:
  qlvbdbhost:
    container_name: qlvbdbhost
    hostname: qlvbdbhost
    image: postgres:12
    env_file:
      - ./.env
    ports:
      - $POSTGRES_EXTERNAL_PORT:$POSTGRES_INTERNAL_PORT
    networks:
      qlvb: null
    restart: unless-stopped
    volumes:
      - $MOUNT_PGDATA:$PGDATA
  qlvbapi:
    container_name: qlvbapi
    hostname: qlvbapi
    env_file:
      - ./.env
    build:
      context: ./base
      dockerfile: Dockerfile
      args:
        - SERVER_INTERNAL_PORT=$SERVER_INTERNAL_PORT
        - POSTGRES_HOST=$POSTGRES_HOST
        - POSTGRES_INTERNAL_PORT=$POSTGRES_INTERNAL_PORT
        - POSTGRES_DB=$POSTGRES_DB
        - POSTGRES_USER=$POSTGRES_USER
        - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
        - API_WORK_DIR=$API_WORK_DIR
    depends_on:
      - qlvbdbhost
    ports:
      - $SERVER_EXTERNAL_PORT:$SERVER_INTERNAL_PORT
    networks:
      qlvb: null
    restart: unless-stopped
    volumes:
      - ./base/src/main/:$API_WORK_DIR/src/main
      - ./base/src/test:$API_WORK_DIR/src/test
      - ./base/target:$API_WORK_DIR/target
      - ./base/libs:$API_WORK_DIR/libs
      - ./base/:$API_WORK_DIR
